#!/usr/bin/env ansible-playbook
#
# This playbook will deploy Mezzanine to vagrant. It contains
# passwords that shwould not be placed in a publicly viewable file if this was
# for a real deployment. Also, the admin_password is ridiculously weak.
#
---
- name: Deploy mezzanine on vagrant
  hosts: vagrant
  gather_facts: True
  vars:
    user: "{{ ansible_ssh_user }}"
    proj_name: mezzanine_example
    proj_path: "{{ ansible_env.HOME}}/{{ proj_name }}"
    conf_path: /etc/nginx/conf
    ssl_enabled: True
    domains:
      - 192.168.33.10.xip.io
      - www.192.168.33.10.xip.io
    venv_path: "{{ ansible_env.HOME }}/venv"
    python: "{{ venv_path }}/bin/python"
    repo: https://github.com/lorin/mezzanine-example.git
    secret_key: 5584232d-e27a-4d2a-94f0-88d2bf5553161843c1ac-3f03-4df7-b3f3-8078192c65fdc007d1b8-b096-4969-a909-613adced709f
    nevercache_key: 3552df47-3d91-4dde-925e-4b1d38cdf9e19d14951c-d5b3-45ed-b91b-4690b841e7e75800eee8-3b1e-4502-87c0-e96945e2519d
    live_hostname: 192.168.33.10.xip.io
    database_name: "{{ proj_name }}"
    database_user: "{{ proj_name }}"
    db_pass: e79c9761d0b54698a83ff3f93769e309
    database_host: localhost
    database_port: 5432
    locale: en_US.UTF-8
    admin_password: password
    gunicorn_port: 8000
    gunicorn_proc_name: mezzanine
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - git
        - libjpeg-dev
        - libpq-dev
        - memcached
        - nginx
        - postgresql
        - python-dev
        - python-pip
        - python-psycopg2
        - python-setuptools
        - python-virtualenv
        - supervisor
    - name: create a virtualenv
      command: virtualenv {{ venv_path }} creates={{ venv_path }}
    - name: install python packages
      pip: name={{ item }} virtualenv={{ venv_path }}
      with_items:
        - mezzanine
        - gunicorn
        - setproctitle
        - south
        - psycopg2
        - django-compressor
        - python-memcached
    - name: check out the repository on the host
      git: repo={{ repo }} dest={{ proj_path }} accept_hostkey=yes ssh_opts="-o ForwardAgent"
    - name: create a user
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ db_pass }}"
      sudo: True
      sudo_user: postgres
    - name: create the database
      postgresql_db:
        name: "{{ database_name }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: "{{ locale }}"
        lc_collate: "{{ locale }}"
        template: template0
      sudo: True
      sudo_user: postgres
    - name: generate the settings file
      template: src=templates/local_settings.py.j2 dest={{ proj_path }}/local_settings.py
    - name: sync the database, apply migrations, collect static content
      django_manage:
        command: "{{ item }}"
        app_path: "{{ proj_path }}"
        virtualenv: "{{ venv_path }}"
      with_items:
        - syncdb
        - migrate
        - collectstatic
    - name: set the site id
      script: scripts/setsite.py
      environment:
        PATH: "{{ venv_path }}/bin"
        PROJECT_DIR: "{{ proj_path }}"
        WEBSITE_DOMAIN: "{{ live_hostname }}"
    - name: set the admin password
      script: scripts/setadmin.py
      environment:
        PATH: "{{ venv_path }}/bin"
        PROJECT_DIR: "{{ proj_path }}"
        ADMIN_PASSWORD: "{{ admin_password }}"
    - name: set the gunicorn config file
      template: src=templates/gunicorn.conf.py.j2 dest={{ proj_path }}/gunicorn.conf.py
    - name: set the supervisor config file
      template: src=templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/mezzanine.conf
      sudo: True
      notify: restart supervisor
    - name: set the nginx config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-enabled/mezzanine.conf
      notify: restart nginx
      sudo: True
    - name: ensure config path exists
      file: path={{ conf_path }} state=directory
      sudo: True
    - name: create ssl certificates
      command: >
        openssl req -new -x509 -nodes -out {{ proj_name }}.crt
        -keyout {{ proj_name}}.key -subj '/CN={{ domains[0] }}' -days 3650
        chdir={{ conf_path }}
        creates={{ conf_path }}/{{ proj_name}}.crt
      sudo: True
      when: ssl_enabled
      notify: restart nginx
  handlers:
    - name: restart supervisor
      supervisorctl: name=gunicorn_mezzanine state=restarted
      sudo: True
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: True

